version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.api.main:app --reload --host 0.0.0.0 --port 8001